name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.20-nullsafety.5
homepage: https://github.com/lejard-h/google_maps_webservice

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  meta: ^1.3.0
  json_annotation: ^4.6.0

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.10.0
  build_runner: ^1.11.0
  json_serializable: ^6.2.0
  coverage: ^1.0.0
