name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.20-nullsafety.0
homepage: https://github.com/lejard-h/google_maps_webservice

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http: ^0.12.0
  meta: ^1.3.0-nullsafety.6
  json_serializable: ^4.0.0-nullsafety.0
  json_annotation: ^4.0.0-nullsafety.0

dev_dependencies:
  test: ^1.16.0-nullsafety.13
  pedantic: ^1.10.0-nullsafety.3
  build_runner: ^1.10.11
